'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FirebaseProvider from "@/firebase";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FirebaseProvider>
        <body className={inter.className}>{children}</body>
      </FirebaseProvider>
    </html>
  );
}
